agents:
  - name: sql_dev
    role: "Senior Database Developer"
    goal: "Construct and execute SQL queries to analyze and validate the database schema and data."
    backstory: |
      You are a highly skilled database engineer. Your responsibilities include constructing efficient SQL queries
      to analyze database metadata and validate schema and data integrity.

      Use the following tools:
      1. `list_tables`: Retrieve the list of available tables in the database.
      2. `tables_schema`: Fetch metadata and structure of specific tables.
      3. `execute_sql`: Execute SQL queries against the database to retrieve data or validate constraints.
      4. `check_sql`: Verify that SQL queries are correct before execution.

      Important: "If the ground truth schema is provided, use it as the definitive reference when generating SQL queries."

  - name: data_validator
    role: "Data Validator"
    goal: "Detect and validate data issues and provide detailed quality statistics."
    backstory: |
      You are a Data Quality Specialist responsible for ensuring data reliability.
      You identify missing values, duplicates, and inconsistencies while summarizing key quality metrics.

  - name: schema_validator
    role: "Schema Validator"
    goal: "Ensure schema relationships are logically consistent and aligned with real-world business rules."
    backstory: |
      You analyze database schema metadata to identify issues such as circular references, unused foreign keys,
      orphaned rows, and misconfigured cascading operations.

  - name: report_writer
    role: "Report Writer"
    goal: "Summarize the results of schema and data validation into actionable insights."
    backstory: |
      You produce clear and structured reports highlighting:
      1. Integrity Checks
      2. Data Validation
      3. Schema Validation Results.

  - name: database_expert
    role: "Database Expert"
    goal: "Fix database issues and save the corrected database into a new one."
    backstory: |
      You generate SQL commands to fix issues identified in the validation process and save the updated database
      as `fixed_<original_database>`. 
      Use `execute_sql` to run the generated SQL scripts against the database.
      Use `save_database` to save the corrected database as a new version.

  - name: prompt_modifier
    role: "Agent Prompt Modifier"
    goal: "Incorporate user modifications (ground truth relationships) into validation prompts and regenerate SQL queries."
    backstory: |
      You analyze user-provided schema updates (from a CSV file) and use them as the ground truth.
      Based on these modifications, you assist the SQL Developer in generating SQL queries that align with
      the updated schema.
      
      Use the following tool:
      1. `read_schema_csv`: Read a CSV file to extract modified schema definitions.

tasks:
  - name: generate_sql
    description: "Extract the list of tables, their schemas, and sample data required for validating the database."
    expected_output: |
      - List of all tables.
      - Schema and up to 3 sample rows for each table.
    agent: sql_dev


  - name: validate_data
    description: "Detect and validate data issues like missing values, duplicates, and inconsistencies."
    expected_output: |
      - Data quality report with missing values, duplicates, and statistics.
    agent: data_validator
    context: [generate_sql]

  - name: validate_schema
    description: "Analyze the database schema for structural issues such as circular references and orphaned rows."
    expected_output: |
      - Schema validation report summarizing structural issues and suggested fixes.
    agent: schema_validator
    context: [generate_sql]

  - name: summarize_results
    description: "Summarize the findings of validation tasks into a structured report."
    expected_output: |
      - Final validation report with data validation, schema validation, and integrity checks.
    agent: report_writer
    context: [validate_data, validate_schema]

  - name: generate_fix_sql
    description: "Generate SQL commands to fix issues and save the corrected database as `fixed_<original>`."
    expected_output: |
      - SQL scripts to fix issues.
      - Database saved as a new corrected version.
    agent: database_expert
    context: [validate_data, validate_schema]

  - name: apply_ground_truth
    description: "Read user-modified schema from a CSV file and apply it as ground truth for SQL generation."
    expected_output: "Ground truth schema extracted and passed for SQL generation."
    agent: prompt_modifier
    config:
      file_path: "./updated_schema.csv"
    context: [generate_sql]

  - name: save_corrected_db
    description: "Save the corrected database into a new database named 'fixed_<original_database>'."
    expected_output: "The corrected database has been saved successfully."
    agent: database_expert
    config:
      new_db_name: "fixed_airportdb"
      source_db_name: "airportdb"
      user: "root"
      password: "9009"
      host: "localhost"
    context: [generate_fix_sql]
